module.exports = [
  ["jst coin", "wnxm coin", "wazirx coin", "wrx coin", "nest protocol"],
  ["nest protocol", "truefi", "tru coin", "df coin", "mantra dao"],
  ["mantra dao", "om coin", "KardiaChain", "kai coin", "sparta coin"],
  ["sparta coin", "data coin", "ton coin", "fio protocol", "fio coin"],
  ["fio coin", "audio coin", "req coin", "thorchain", "rune coin"],
  ["rune coin", "populous coin", "ppt coin", "ignis coin", "lamb coin"],
  ["lamb coin", "TT coin", "front coin", "wozx coin", "efforce"],
  ["efforce", "firo coin", "aavegotchi", "ghst coin", "wicc coin"],
  ["wicc coin", "everest coin", "id coin", "anyswap", "certik coin"],
  ["certik coin", "ctk coin", "dao maker", "dao coin", "esd coin"],
  ["esd coin", "unilend", "ring coin", "aeth coin", "origin protocol"],
  ["origin protocol", "OGN coin", "kobe coin", "tellor", "trb coin"],
  ["trb coin", "bscx coin", "yield app", "yld coin", "uysd"],
  ["uysd", "bZx protocol", "bzrx coin", "DIGG coin", "pirate coin"],
  ["pirate coin", "Centrality coin", "cennz coin", "Velas coin", "vlx coin"],
  ["vlx coin", "DIA coin", "Frax Share", "fxs coin", "Morpheus Network"],
  ["Morpheus Network", "mrph coin", "NULS coin", "SmartKey coin", "ZB Token"],
  ["ZB Token", "cBAT coin", "Zenon coin", "Einsteinium coin", "Keep3rV1"],
  ["Keep3rV1", "KP3R coin", "Cartesi coin", "Aeternity coin", "AE coin"],
  ["AE coin", "Cover Protocol", "PAID Network", "Nimiq", "nim coin"],
  ["nim coin", "Carry coin", "Telos", "Ferrum Network", "frm coin"],
  ["frm coin", "Auto coin", "Bounce coin", "AUCTION coin", "SOLVE coin"],
  ["SOLVE coin", "Marlin coin", "POND coin", "Groestlcoin", "GRS coin"],
  ["GRS coin", "BoringDAO", "bor coin", "Rarible coin", "rari coin"],
  ["rari coin", "Bao Finance", "bao coin", "Zap coin", "APY.Finance"],
  ["APY.Finance", "BitZ Token", "BZ coin", "pNetwork", "pnt coin"],
  ["pnt coin", "Unit Protocol", "DUCK coin", "Bella Protocol", "bel coin"],
  ["bel coin", "opium coin", "Etherisc DIP Token", "dip coin", "BEAM coin"],
  ["BEAM coin", "Minter coin", "bip coin", "oxen coin", "DLP Duck Token"],
  ["DLP Duck Token", "Medibloc", "med coin", "Skycoin", "sky coin"],
  ["sky coin", "atari coin", "Enzyme coin", "VSYS coin", "Bluzelle"],
  ["Bluzelle", "blz coin", "umi coin", "umi coin", "DexTools"],
  ["DexTools", "dext coin", "Contentos coin", "cos coin", "Kadena"],
  ["Kadena", "STP Network", "Meta coin", "MTA coin", "cVault.finance"],
  ["cVault.finance", "Elastos", "elastos coin", "HyperCash", "hc coin"],
  ["hc coin", "Terra Virtua", "tvk coin", "mork coin", "YAM coin"],
  ["YAM coin", "Value Liquidity coin", "AirSwap", "AST coin", "Steem Dollars"],
  ["Steem Dollars", "sbd coin", "steem coin", "Bonfida coin", "fida coin"],
  ["fida coin", "Meme coin", "Shopping.io", "spi coin", "Zero Exchange"],
  ["Zero Exchange", "zero coin", "MetaHash", "mhc coin", "NSBT coin"],
  ["NSBT coin", "Phantasma", "soul coin", "Umbrella Network", "umb coin"],
  ["umb coin", "Ripio Credit Network", "rcn coin", "ARPA Chain", "arpa coin"],
  ["arpa coin", "SportX coin", "sx coin", "GXChain", "gxc coin"],
  ["gxc coin", "ACryptoS", "acs coin", "Rubic coin", "rbc coin"],
  ["rbc coin", "88mph", "mph coin", "Neblio", "nebl coin"],
  ["nebl coin", "Bidao", "bid coin", "Waltonchain", "wtc coin"],
  ["wtc coin", "IDEX", "Vertcoin", "vtc coin", "Chain Games"],
  ["Chain Games", "chain coin", "Bitpanda coin", "Render Token", "rndr coin"],
  ["rndr coin", "Plasma Finance", "ppay coin", "Sentinel coin", "sent coin"],
  ["sent coin", "Sirin Labs Token", "srn coin", "Cindicator", "cnd coin"],
];