// module.exports = [
//   ["jst coin", "wnxm coin", "wazirx coin", "wrx coin", "nest protocol"],
//   ["nest protocol", "truefi", "tru coin", "df coin", "mantra dao"],
//   ["mantra dao", "om coin", "KardiaChain", "kai coin", "sparta coin"],
//   ["sparta coin", "data coin", "ton coin", "fio protocol", "fio coin"],
//   ["fio coin", "audio coin", "req coin", "thorchain", "rune coin"],
//   ["rune coin", "populous coin", "ppt coin", "ignis coin", "lamb coin"],
//   ["lamb coin", "TT coin", "front coin", "wozx coin", "efforce"],
//   ["efforce", "firo coin", "aavegotchi", "ghst coin", "wicc coin"],
//   ["wicc coin", "everest coin", "id coin", "anyswap", "certik coin"],
//   ["certik coin", "ctk coin", "dao maker", "dao coin", "esd coin"],
//   ["esd coin", "unilend", "ring coin", "aeth coin", "origin protocol"],
//   ["origin protocol", "OGN coin", "kobe coin", "tellor", "trb coin"],
//   ["trb coin", "bscx coin", "yield app", "yld coin", "uysd"],
//   ["uysd", "bZx protocol", "bzrx coin", "DIGG coin", "pirate coin"],
//   ["pirate coin", "Centrality coin", "cennz coin", "Velas coin", "vlx coin"],
//   ["vlx coin", "DIA coin", "Frax Share", "fxs coin", "Morpheus Network"],
//   ["Morpheus Network", "mrph coin", "NULS coin", "SmartKey coin", "ZB Token"],
//   ["ZB Token", "cBAT coin", "Zenon coin", "Einsteinium coin", "Keep3rV1"],
//   ["Keep3rV1", "KP3R coin", "Cartesi coin", "Aeternity coin", "AE coin"],
//   ["AE coin", "Cover Protocol", "PAID Network", "Nimiq", "nim coin"],
//   ["nim coin", "Carry coin", "Telos", "Ferrum Network", "frm coin"],
//   ["frm coin", "Auto coin", "Bounce coin", "AUCTION coin", "SOLVE coin"],
//   ["SOLVE coin", "Marlin coin", "POND coin", "Groestlcoin", "GRS coin"],
//   ["GRS coin", "BoringDAO", "bor coin", "Rarible coin", "rari coin"],
//   ["rari coin", "Bao Finance", "bao coin", "Zap coin", "APY.Finance"],
//   ["APY.Finance", "BitZ Token", "BZ coin", "pNetwork", "pnt coin"],
//   ["pnt coin", "Unit Protocol", "DUCK coin", "Bella Protocol", "bel coin"],
//   ["bel coin", "opium coin", "Etherisc DIP Token", "dip coin", "BEAM coin"],
//   ["BEAM coin", "Minter coin", "bip coin", "oxen coin", "DLP Duck Token"],
//   ["DLP Duck Token", "Medibloc", "med coin", "Skycoin", "sky coin"],
//   ["sky coin", "atari coin", "Enzyme coin", "VSYS coin", "Bluzelle"],
//   ["Bluzelle", "blz coin", "umi coin", "umi coin", "DexTools"],
//   ["DexTools", "dext coin", "Contentos coin", "cos coin", "Kadena"],
//   ["Kadena", "STP Network", "Meta coin", "MTA coin", "cVault.finance"],
//   ["cVault.finance", "Elastos", "elastos coin", "HyperCash", "hc coin"],
//   ["hc coin", "Terra Virtua", "tvk coin", "mork coin", "YAM coin"],
//   ["YAM coin", "Value Liquidity coin", "AirSwap", "AST coin", "Steem Dollars"],
//   ["Steem Dollars", "sbd coin", "steem coin", "Bonfida coin", "fida coin"],
//   ["fida coin", "Meme coin", "Shopping.io", "spi coin", "Zero Exchange"],
//   ["Zero Exchange", "zero coin", "MetaHash", "mhc coin", "NSBT coin"],
//   ["NSBT coin", "Phantasma", "soul coin", "Umbrella Network", "umb coin"],
//   ["umb coin", "Ripio Credit Network", "rcn coin", "ARPA Chain", "arpa coin"],
//   ["arpa coin", "SportX coin", "sx coin", "GXChain", "gxc coin"],
//   ["gxc coin", "ACryptoS", "acs coin", "Rubic coin", "rbc coin"],
//   ["rbc coin", "88mph", "mph coin", "Neblio", "nebl coin"],
//   ["nebl coin", "Bidao", "bid coin", "Waltonchain", "wtc coin"],
//   ["wtc coin", "IDEX", "Vertcoin", "vtc coin", "Chain Games"],
//   ["Chain Games", "chain coin", "Bitpanda coin", "Render Token", "rndr coin"],
//   ["rndr coin", "Plasma Finance", "ppay coin", "Sentinel coin", "sent coin"],
//   ["sent coin", "Sirin Labs Token", "srn coin", "Cindicator", "cnd coin"],
// ];
module.exports = [
  ["0chain", "1inch", "1INCH coin", "88mph", "aavegotchi"],
  ["acs coin", "ADAI coin", "adex coin", "ADX coin", "AE coin"],
  ["Aeternity coin", "aeth coin", "AGI coin", "aion coin", "AirSwap"],
  ["akash network", "AKRO coin", "akropolis coin", "AKT coin", "ALBT coin"],
  ["Aleph.im", "ALGO coin", "algorand", "allianceblock", "ALPHA coin"],
  ["Alpha Quark", "AMPL coin", "ampleforth", "ANKR coin", "ANT coin"],
  ["api3", "API3 coin", "APL coin", "Apollo coin", "APY.Finance"],
  ["aragon coin", "ardor coin", "ARDR coin", "ARK coin", "ARMOR coin"],
  ["arpa coin", "AST coin", "atari coin", "AUCTION coin", "audio coin"],
  ["AUSDC coin", "Auto coin", "AVA coin", "AXEL coin", "axie infinity"],
  ["AXN coin", "AXS coin", "BAC coin", "BADGER coin", "badger dao"],
  ["balancer coin", "BAND coin", "band protocol", "bao coin", "Bao Finance"],
  ["BAS coin", "Basis Share", "BCD coin", "BCHA coin", "BCN coin"],
  ["beefy.finance", "bel coin", "Bella Protocol", "Berry Data", "bid coin"],
  ["BIFI coin", "bip coin", "bitcoin diamond", "Bitpanda coin", "bitshares"],
  ["BitZ Token", "BLOCK coin", "Bluzelle", "blz coin", "BMI coin"],
  ["BOND coin", "bondly coin", "Bonfida coin", "bor coin", "BoringDAO"],
  ["BOT coin", "bounce coin", "Bounce coin", "Bridge Mutual", "BRY coin"],
  ["btc standard hashrate token", "BTC2 coin", "BTCST coin", "BTM coin", "BTS coin"],
  ["bytecoin coin", "bytom", "BYTS coin", "BZ coin", "bzrx coin"],
  ["c0x coin", "C20 coin", "CARD coin", "Cardstack", "Carry coin"],
  ["CAS coin", "cashaa", "cBAT coin", "CC10", "CC10 coin"],
  ["celo coin", "CELR coin", "cennz coin", "Centrality coin", "certik coin"],
  ["chain coin", "Chain Games", "chainx", "chiliz coin", "CHR coin"],
  ["CHZ coin", "Cindicator", "civic coin", "CKB coin", "cnd coin"],
  ["COCOS coin", "coinmetro", "constellation coin", "Contentos coin", "Cortex coin"],
  ["coti", "COTI coin", "COVER coin", "Cover Protocol", "CREAM coin"],
  ["CRETH2 coin", "CRPT coin", "CRU coin", "Crust Network", "ctk coin"],
  ["CUNI coin", "cusdt", "CUSDT coin", "cVault.finance", "CVC coin"],
  ["CyberFi", "CZRX coin", "DAG coin", "dao coin", "dao maker"],
  ["DDIM coin", "DDX coin", "DEC coin", "DEC2 coin", "Decentr"],
  ["decentraland", "DEFI5", "DEFI5 coin", "defipulse", "DEGO coin"],
  ["dent coin", "derivadao", "DERO coin", "DEXE coin", "DeXe • DEXE"],
  ["DEXTF coin", "DEXTF", "DexTools", "df coin", "dfi.money"],
  ["DGD coin", "dHEDGE DAO", "DHT coin", "DIA coin", "DIGG coin"],
  ["dip coin", "district0x", "DLP Duck Token", "DMarket", "DMT coin"],
  ["DOCK coin", "DODO coin", "DPI coin", "Dragonchain", "DRGN coin"],
  ["duckdaodime", "DUSK coin", "dusk network", "EASY coin", "EasyFi"],
  ["edgeware", "Effect.AI", "efforce", "EFX coin", "EGG coin"],
  ["Elastos", "elastos coin", "electroneum coin", "elf coin", "ELG coin"],
  ["energy web token", "Enzyme coin", "e-radix", "ERG coin", "ergo coin"],
  ["Etherisc DIP Token", "ETN coin", "everest coin", "EVN coin", "Evolution Finance"],
  ["ExNetwork Token", "EXNT coin", "EXRD coin", "Falcon Project", "FARM coin"],
  ["FET coin", "fetch.ai", "fida coin", "FILDA coin", "Finxflo"],
  ["fio protocol", "firo coin", "FIS coin", "flexacoin coin", "FNT coin"],
  ["ForTube", "FRAX coin", "Frax Share", "frm coin", "front coin"],
  ["FUN coin", "funfair", "FUSION coin", "FWB coin", "FX coin"],
  ["FXF coin", "fxs coin", "GALA coin", "GAS coin", "gatetoken"],
  ["Genesis Vision • GVT", "GET coin", "GET Protocol", "ghst coin", "GivingToServices"],
  ["GNO coin", "gnosis coin", "GO coin", "GoChain", "golem coin"],
  ["GRIN coin", "Groestlcoin", "GRS coin", "GT coin", "GUSD coin"],
  ["gxc coin", "GXChain", "HAI coin", "handshake coin", "HARD coin"],
  ["harmony coin", "harvest finance", "hathor", "haven coin", "hc coin"],
  ["HEGIC coin", "helium coin", "Hermez Network", "HEZ coin", "hifi finance"],
  ["HNS coin", "HNT coin", "HTR coin", "hxro", "HXRO coin"],
  ["id coin", "IDEX", "IDLE coin", "IETH coin", "iETH"],
  ["ignis coin", "INDEX coin", "Index Cooperative", "INJ coin", "injective protocol"],
  ["IOTX coin", "IRIS coin", "irisnet", "Jibrel Network", "JNT coin"],
  ["JUL coin", "JULD coin", "JULIEN coin", "julswap", "justliquidity"],
  ["kai coin", "KardiaChain", "KAVA coin", "kava.io", "KCS coin"],
  ["keep network", "Keep3rV1", "keeperdao", "KEX coin", "KEY coin"],
  ["Kleros coin", "KMD coin", "KNC coin", "kobe coin", "komodo coin"],
  ["kucoin token", "kyber network", "lamb coin", "LBC coin", "lbry credits"],
  ["LGCY coin", "LGCY Network", "LGO coin", "lgo token coin", "LINA coin"],
  ["lisk coin", "LIT coin", "litentry", "livepeer", "LOC coin"],
  ["LOOM coin", "loom network", "LPT coin", "LSK coin", "LTO coin"],
  ["LUA coin", "Lua Token", "MAID coin", "maidsafecoin", "MANA coin"],
  ["Marlin coin", "MASK coin", "mask network", "MATH coin", "MBX coin"],
  ["MCDEX", "MDT coin", "Measurable Data", "med coin", "Medibloc"],
  ["MET coin", "Meta coin", "MetaHash", "metal coin", "Metronome coin"],
  ["MFT coin", "mhc coin", "mimblewimblecoin", "Minter coin", "MIR coin"],
  ["MobieCoin", "MONA coin", "monacoin", "mork coin", "Morpheus Network"],
  ["mrph coin", "MTA coin", "MTL coin", "MTLX coin", "MTXLT coin"],
  ["MUSE coin", "MWC coin", "MX coin", "mx token", "MXC coin"],
  ["namecoin", "NAS coin", "NAV coin", "NavCoin", "NCP coin"],
  ["Neblio", "Nebulas coin", "NEC coin", "nervos network", "nest protocol"],
  ["nexus coin", "nexus mutual", "nftx", "NFTX coin", "nim coin"],
  ["NKN coin", "NMC coin", "NMR coin", "NOIA coin", "NRG coin"],
  ["NU coin", "nucypher", "NULS coin", "numeraire", "NWC coin"],
  ["NXS coin", "NXT coin", "NYE coin", "oasis network", "OCEAN coin"],
  ["OCTO coin", "OctoFi", "OGN coin", "OKB coin", "om coin"],
  ["opium coin", "OptionRoom", "ORAI coin", "Oraichain", "ORBS coin"],
  ["origintrail", "orion protocol", "ORN coin", "oxen coin", "PAC coin"],
  ["parsiq", "pax gold", "PAXG coin", "pBTC35A", "PBTC35A coin"],
  ["PEAK coin", "PEAKDEFI", "PERP coin", "perpetual protocol", "PHA coin"],
  ["Phantasma", "Phoenix Global", "PHX coin", "PIB coin", "Pibble coin"],
  ["pivx", "PIVX coin", "Plasma Finance", "PLTC coin", "pNetwork"],
  ["pnt coin", "polkastarter", "POLS coin", "POLY coin", "polymath network"],
  ["POOL coin", "PoolTogether", "POOLZ coin", "Poolz Finance", "populous coin"],
  ["PowerPool", "PowerTrade Fuel", "POWR coin", "ppay coin", "ppt coin"],
  ["Presearch", "PROM coin", "prometeus", "PROS coin", "Prosper coin"],
  ["PTF coin", "QASH coin", "QASH", "QKC coin", "QNT coin"],
  ["QSP coin", "quant coin", "Quantstamp", "quarkchain", "Raiden Network Token"],
  ["RAMP coin", "rari coin", "rari governance", "Rarible coin", "RAY coin"],
  ["rbc coin", "rcn coin", "RDD coin", "RDN coin", "reddcoin"],
  ["Refereum coin", "Render Token", "REP coin", "REPO coin", "req coin"],
  ["RFOX coin", "RFR coin", "RFUEL coin", "RGT coin", "RIF coin"],
  ["RioDeFi", "Ripio Credit Network", "RLC coin", "RLY coin", "rndr coin"],
  ["rocket pool", "ROOK coin", "ROOM coin", "ROSE coin", "RPL coin"],
  ["Rubic coin", "RUFF coin", "rune coin", "safepal coin", "saffron.finance"],
  ["SALT coin", "SAND coin", "sbd coin", "SBTC coin", "SCRT coin"],
  ["secret coin", "SelfKey", "sent coin", "Sentinel Protocol", "Sentinel coin"],
  ["SERO coin", "serum coin", "SETH coin", "SFI coin", "SFP coin"],
  ["sharetoken", "SHIFT coin", "Shopping.io", "SHR coin", "singularitynet"],
  ["skale coin", "SKL coin", "sky coin", "Skycoin", "SLT coin"],
  ["Smartlands Network", "SNL coin", "SNT coin", "SNTVT coin", "SOCKS coin"],
  ["sora coin", "sora validator", "soul coin", "sparta coin", "Spendcoin"],
  ["SPND coin", "Sport and Leisure coin", "SportX coin", "SRM coin", "srn coin"],
  ["STAKE coin", "Stake DAO", "stakehound", "status coin", "steem coin"],
  ["STETH coin", "STMX coin", "storj coin", "stormx coin", "STP Network"],
  ["STRAX coin", "SUKU coin", "SUKU", "SUPER coin", "superfarm"],
  ["SVCS coin", "SWAP coin", "SWG coin", "swingby", "SWINGBY coin"],
  ["Swirge", "Switcheo", "SWTH coin", "sx coin", "SXP coin"],
  ["SYS coin", "syscoin", "TBTC coin", "TEL coin", "telcoin"],
  ["Telos", "Terra Virtua", "TFUEL coin", "theta fuel", "thorchain"],
  ["titanswap", "Tixl", "tokenlon", "TOMO coin", "tomochain"],
  ["TORN coin", "tornado cash", "TRAC coin", "travala.com", "trb coin"],
  ["truefi", "trust wallet token", "trustswap", "TRYB coin", "TT coin"],
  ["tvk coin", "TWT coin", "TXL coin", "UBT coin", "ULT coin"],
  ["umb coin", "Umbrella Network", "umi coin", "UNFI coin", "unibright"],
  ["unilend", "UNION Protocol", "Unisocks", "UNISTAKE coin", "Unistake"],
  ["UNN coin", "UOS coin", "UPP coin", "UQC coin", "uquid coin"],
  ["USDN coin", "UTK coin", "utrust coin", "uysd", "vai coin"],
  ["Value Liquidity  coin", "Vectorspace AI", "Velas coin", "venus coin", "verge coin"],
  ["Vesper Finance", "vethor token", "VID coin", "VideoCoin", "VIDT coin"],
  ["VITAE coin", "vlx coin", "VRS coin", "VRSC coin", "VSP coin"],
  ["vtc coin", "VTHO coin", "VXV coin", "Waltonchain", "WAN coin"],
  ["wax coin", "WAXP coin", "wazirx coin", "whale coin", "WHITE coin"],
  ["wicc coin", "WIN coin", "WING coin", "Wing Finance", "wink coin"],
  ["wnxm coin", "WOM coin", "WOM Protocol", "WOO coin", "wootrade network"],
  ["wrx coin", "wtc coin", "WXT coin", "XAUT coin", "XCM coin"],
  ["XDB coin", "XDC coin", "xdc network", "XHV coin", "XOR coin"],
  ["XVG coin", "XVS coin", "YAM coin", "YCC coin", "YFII coin"],
  ["yld coin", "YOP coin", "yuan chain coin", "ZAI coin", "ZANO coin"],
  ["ZB Token", "ZCN coin", "ZEE coin", "Zenon coin", "zero coin"],
  ["Zero Exchange", "ZeroSwap", "Zipmex Token", "ZMT coin", "AITRA coin"],
  ["ERSDL coin", "YLD coin", "YOP coin", "SAFE2 coin", "FUEL coin"],
  ["PAY coin", "PMA coin", "ZT coin", "SNOW coin", "BFC coin"],
  ["FCT coin", "NDX coin", "JRT coin", "1ST coin", "HUNT coin"],
  ["HYDRA coin", "DEA coin", "MIX coin", "XED coin", "L2 coin"],
  ["DSLA coin", "FWT coin", "CBC coin", "EHRT coin", "MOC coin"],
  ["CUDOS coin", "MARK coin", "ENG coin", "ICHI coin", "GTH coin"],
  ["YAX coin", "POA coin", "OPEN coin", "VIA coin", "COIN coin"],
  ["SMART coin", "UBQ coin", "BYTZ coin", "BDT coin", "GOVI coin"],
  ["PBTC coin", "BNK coin", "TOP coin", "OAX coin", "PBR coin"],
  ["SHROOM coin", "ETP coin", "COL coin", "BWF coin", "NGM coin"],
  ["YVE-CRVDAO coin", "PRO coin", "DUSD coin", "TRTT coin", "QLC coin"],
  ["IQN coin", "CUT coin", "SHA coin", "OST coin", "BEPRO coin"],
  ["YFL coin", "GTO coin", "HAKKA coin", "CLO coin", "LDO coin"],
  ["HYN coin", "ONX coin", "WPR coin", "ZEFU coin", "BBR coin"],
  ["EDR coin", "PREMIA coin", "CS coin", "WAULT coin", "NEBO coin"],
  ["RKN coin", "QNTU coin", "UNCX coin", "MITX coin", "SWRV coin"],
  ["NEX coin", "RFI coin", "TERN coin", "MUST coin", "DEUS coin"],
  ["ABT coin", "DCN coin", "ABYSS coin", "VEE coin", "WABI coin"],
  ["CDT coin", "TAU coin", "FSW coin", "MBL coin", "CSC coin"],
  ["XMY coin", "BIX coin", "EVX coin", "MAAPL coin", "MNTIS coin"],
  ["EUNO coin", "KEBAB coin", "REAP coin", "LCX coin", "FNX coin"],
  ["UDOO coin", "DOS coin", "SPC coin", "UTNP coin", "HYDRO coin"],
  ["SAN coin", "AOA coin", "DYN coin", "LAYER coin", "FREE coin"],
  ["PPC coin", "DUST coin", "PICKLE coin", "FTC coin", "UNC coin"],
  ["NSURE coin", "PLU coin", "XMX coin", "SNGLS coin", "DSD coin"],
  ["SDEFI coin", "GEN coin", "SIX coin", "LIKE coin", "EPIC coin"],
  ["SLP coin", "UBXT coin", "BFT coin", "SWFTC coin", "FOAM coin"],
  ["DTA coin", "ESS coin", "DLT coin", "CMT coin", "MAHA coin"],
  ["EAC coin", "DXD coin", "XST coin", "VALOR coin", "CNTR coin"],
  ["SLINK coin", "XDN coin", "SNM coin", "CRDT coin", "GXT coin"],
  ["ACT coin", "FLO coin", "VIB coin", "BOND coin", "BMC coin"],
  ["SATT coin", "EMC coin", "USDP coin", "SASHIMI coin", "AUC coin"],
  ["DRC coin", "OWC coin", "TIPS coin", "SYNX coin", "CREP coin"],
  ["MOD coin", "NIOX coin", "SMT coin", "OCE coin", "GNX coin"],
  ["DITTO coin", "COFI coin", "TKN coin", "LYM coin", "APPC coin"],
  ["ZEL coin", "DOKI coin", "CXO coin", "AGA coin", "MYST coin"],
  ["RARE coin", "WGR coin", "GAME coin", "BTX coin", "BULL coin"],
  ["BIRD coin", "OPCT coin", "GRO coin", "NCT coin", "APM coin"],
  ["LIEN coin", "POT coin", "UNIFI coin", "LEAD coin", "SCC coin"],
  ["DOUGH coin", "XCASH coin", "ZHEGIC coin", "COS coin", "PND coin"],
  ["KLP coin", "KOGE coin", "PHR coin", "DMD coin", "MTH coin"],
  ["SPANK coin", "TNB coin", "PRT coin", "RBASE coin", "LET coin"],
  ["GEEQ coin", "FLEX coin", "42 coin", "COMP coin", "EZW coin"],
  ["YUKI coin", "CWBTC coin", "TAD coin", "DTX coin", "AOG coin"],
  ["SEEN coin", "LCC coin", "XCUR coin", "SWAG coin", "FUND coin"],
  ["MDS coin", "STRONG coin", "VEO coin", "SMARTCREDIT coin", "NIX coin"],
  ["THUGS coin", "BOLT coin", "COV coin", "CHX coin", "DEPAY coin"],
  ["BITCNY coin", "DUN coin", "XCP coin", "STBZ coin", "BMX coin"],
  ["ODE coin", "DBC coin", "OUSD coin", "AC coin", "ASSY coin"],
];
